name: Lint the project
on: [push, pull_request]
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
