name: Sync base branches
on:
  push:
    branches:
      - main
      - develop
jobs:
  sync-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v2
        with:
          version: "8"
          run_install: true
      - run: npm run test:coverage
      - uses: codecov/codecov-action@v3
