name: Validate pull request
on: pull_request
jobs:
  run-validations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v2
        with:
          version: "8"
          run_install: true
      - run: pnpm run format:check
      - run: pnpm run lint
      - run: pnpm run test:coverage
      - uses: codecov/codecov-action@v3
